### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by xperiandri** [radiy/vs-graphql-textmate#5]
Will you approve the pull request that migrates extension to support VS 2022? I mean dropping support of 2019 and earlier.

**Comment by radiy** [comment]
Any specific reason to drop 2019?

**Comment by xperiandri** [comment]
In order to support to 2019 you need to create one more VSIX project for 2022. And share same code via shared project.
Single project can't work for both x86 and x64

**Comment by radiy** [comment]
I would prefer just to create a separate project file for 2022, like this https://github.com/VsVim/VsVim/tree/master/Src/VsVim2022.

**Comment by xperiandri** [comment]
Are you going to add any more functionality to your extension?

**Comment by radiy** [comment]
Let`s start simple, assume that vs2019 is frozen and new functionality will be in vs2020, of course, if there is one.

**Comment by radiy** [comment]
Take a look at #6, I think this is what you need.

**Comment by xperiandri** [comment]
Yes, I instructed him how to perform a migration
